name: Release

on:
  push:
    tags:
      - '*'  
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  crawl:
    name: Crawl Domains
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python program
        run: |
          python src/main.py

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: generated-domains
          path: |
            data/ir_domains.txt
            data/other_domains.txt
            
      - name: Upload result as release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "data/*.txt"
          token: ${{ secrets.GITHUB_TOKEN }}


#   v2ray:
#     name: V2ray Dat File
#     needs: crawl
#     runs-on: ubuntu-latest
#     steps:
#       - name: Setup Go
#         uses: actions/setup-go@v2
#         with:
#           go-version: ^1.15

#       - name: Download result of crawl job
#         uses: actions/download-artifact@v2
#         with:
#           name: generated-domains
