name: Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  crawl:
    name: Crawl Domains
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Env
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python program
        run: |
          python src/main.py

      - name: Check result files
        run: |
          total=$(wc -l output/*.txt | awk 'END {print $1}')
          formatted_total=$(LC_NUMERIC=en_US printf "%'.f\n" $total)
          old=$(curl -sSL --connect-timeout 5 -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/SamadiPour/iran-hosted-domains/releases/latest | grep "body" | cut -d\" -f4 | cut -d " " -f1)          

          if [[ $formatted_total -ne $old ]]; then
            echo "SHOULD_UPDATE=true" >> $GITHUB_ENV
          fi

          echo "TOTAL_DOMAINS=$formatted_total" >> $GITHUB_ENV

      - name: Upload result as release
        if: ${{ env.SHOULD_UPDATE }}
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.*"
          body: "${{ env.TOTAL_DOMAINS }} Domains"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
