name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go 1.x.y
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run python program
        run: |
          python src/main.py

      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: generated-domains
          path: |
            data/ir_domains
            data/other_domains
